### ISSUE TITLE
Calling Your Platform "Learn"

### ISSUE THREAD

**Issue by bberastain** [rmotr-curriculum/meta-how-to-use-learn#1]
Feels inconvenient because I have do what should be an unnecessary translation from verb to noun every time I read it, just a thought but even if I end up loving this program I already see the process of explaining that to whoever I recommend it to being annoying.

From your "External Assignment Lesson"
An external assignment lesson is also a lesson that contains a practical coding exercise, but instead of do it in learn, you will have to submit a pull request.

**Comment by santiagobasulto** [comment]
That is true indeed. We were trying to find a better name but didn't find any :/ What's the issue with External assignments?

**Comment by bberastain** [comment]
No particular issue, this was just the easiest way to give feedback, im
enjoying your Intro to HTTP lesson right now, thank you!

**Comment by santiagobasulto** [comment]
Thank you! Let us know if you have issues
